name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure .env is not in the repository
        run: |
          if git ls-files --error-unmatch .env > /dev/null 2>&1; then
            echo ".env is tracked in the repository - remove it and re-run" >&2
            exit 1
          fi

      - name: Run tests
        run: pytest -q
